### ISSUE TITLE
Cloudflare Proxy blocking our visitors IP address

### ISSUE THREAD

**Issue by stuartm21** [soulbalz/traefik-real-ip#7]
Hi,

We are using this plugin to find the IP address of our visitors, but after enabling the Cloudflare proxy, we are seeing CF IP's in the log/api. How can we see the visitor's IP address with Cloudflare proxy? We are running our apps in Kubernetes with Traefik 2.7 app.
Our middleware is:
```
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-real-ip
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        - "1.1.1.1/24"
```
